### ISSUE TITLE
Frontend Registration - Customer

### ISSUE THREAD

**Issue by chrisp-dev** [chrisp-dev/rad-project#28]
As a User
I want to be able to register my customer info

**Comment by julie-git** [comment]
What is the error?

**Comment by chrisp-dev** [comment]
First name and last name are not saving to the DB

**Comment by chrisp-dev** [comment]
Resolved. Julie is continuing to work on finishing registration

**Comment by julie-git** [comment]
Fixed duplicate script main.js on index handlebar file
