### ISSUE TITLE
Look up handyman availability

### ISSUE THREAD

**Issue by aritse** [chrisp-dev/rad-project#35]
A customer submits a service title and a date of the service to the server. The server queries the database with the service title and the date and picks the necessary number of handyman and responds with several time slots to the customer.

**Comment by aritse** [comment]
Let's keep it simple for the MVP 0. Looking up the availability is a bit complicated. A customer should be able to submit a SR by choosing the SR title and date and get a confirmation back. The SR is unassigned at this time. A handyman view after the login in should have at least two links - one to view SRs assigned to him and another to view all SRs either unassigned and assigned to other handmen. A handyman will be able to assign a SR to himself.

**Comment by chrisp-dev** [comment]
Was able to complete /api/handymans GET to accept query param Date and will return all handymans with their assigned SRs for the day.
